### ISSUE TITLE
Add events/notifications support

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet-contrib/AspNet.Security.OAuth.Extensions#2]
Objective: adding a new `events` interface/class to both the validation and the introspection middleware, similarly to what the JWT bearer middleware offers: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.JwtBearer/Events/IJwtBearerEvents.cs

**Comment by DovydasNavickas** [comment]
You can assign it to me. First I hope to finish samples here:
https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples/issues/3

And then take this one.

**Comment by PinpointTownes** [comment]
@DovydasNavickas hey!

Do you still want to take this one? :smile:

**Comment by DovydasNavickas** [comment]
First of all, the link you gave got broken when Microsoft renamed `AspNet` to `AspNetCore`, so, new link to `IJwtBearerEvents.cs` is here:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.JwtBearer/Events/IJwtBearerEvents.cs

Secondly, if it's not urgent like "we need it tomorrow", then I can start working on it between my own stuff.
As I see, it is not really complicated, just the initial sit down with the code took almost two months.. :smile: (as always)

Anyways, I've started some of the stuff here:
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/pull/11

**Comment by PinpointTownes** [comment]
Merged: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/commit/a1951c76fbe76edb98e28bdf64b69651aa74d3e1.

Thanks for your contribution :clap:
