### ISSUE TITLE
"jti" claim support

### ISSUE THREAD

**Issue by MonkeyJamboree** [aspnet-contrib/AspNet.Security.OAuth.Extensions#28]
As indicated in https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/246, we should restore the "jti" claim that comes from the token introspection endpoint to some sort of property on the Resource Server side.

What should this property or claim be named?

**Comment by MonkeyJamboree** [comment]
Also, should this be done on the "release" branch for consistency with ASOS?

**Comment by PinpointTownes** [comment]
> What should this property or claim be named?

Per your suggestion, `ticket_id`.

> Also, should this be done on the "release" branch for consistency with ASOS?

Yep, please :clap:

**Comment by PinpointTownes** [comment]
Implemented: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/commit/4bdc5ae8b6db735267559c6e67597a2c11ff786b.

@MonkeyJamboree thanks for your contribution :clap:
