### ISSUE TITLE
UseOAuthIntrospection() And Use Role not work

### ISSUE THREAD

**Issue by Lissbrict** [aspnet-contrib/AspNet.Security.OAuth.Extensions#49]
#### Resource server Use UseOAuthIntrospection() And Use Role not work

- Resource server config

```
 app.UseOAuthIntrospection(options =>
            {
                options.DataProtectionProvider = new EphemeralDataProtectionProvider();
                options.AutomaticAuthenticate = true;
                options.AutomaticChallenge = true;
                options.Authority = "http://localhost:9681";
                options.ClientId = "5FD848E5D5574F349571D77CE56CB898";
                options.ClientSecret = "123456789";
                options.SaveToken = false;
            });
``` 
- possible problem is ...
 1. AuthorizeService ->access_token
 2. access_token -> Resource server -> Controller -> User
 3. User.Identitie Role Key is `Role` but User.IsInRole("xx") need role key is `ClaimTypes.Role` , value=`http://schemas.microsoft.com/ws/2008/06/identity/claims/role`
 4. Use UseOAuthValidation() is Success
 5. ``` this is config error or bug? ```

thank you..

**Comment by Lissbrict** [comment]
rumtime log:

- The same token:....


#### UseOAuthIntrospection()
- User.Claims
    - "iss": "http://localhost:9681/",
    - "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "a0c75c3a8d504b7faaf1c004586ac36c",
    - "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": "13881986173",
    - "scope": "offline_access",
    - "scope": "roles",
    - "unique_name": "13881986173",
    - "AspNet.Identity.SecurityStamp": "e73b9998-f790-4646-b7eb-49a82d3d2934",
    - "role": "Driver"  // this key is `Role`

#### UseOAuthValidation()
- User.Claims
    - "iss": "http://localhost:9681/",
    - "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "a0c75c3a8d504b7faaf1c004586ac36c",
    - "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": "13881986173",
    - "scope": "offline_access",
    - "scope": "roles",
    - "unique_name": "13881986173",
    - "AspNet.Identity.SecurityStamp": "e73b9998-f790-4646-b7eb-49a82d3d2934",
    - "http://schemas.microsoft.com/ws/2008/06/identity/claims/role": "Driver"  // this key is `http://schemas.microsoft.com/ws/2008/06/identity/claims/role`

**Comment by PinpointTownes** [comment]
You should really try to make complete sentences. Otherwise, it's impossible to help you :fearful:

**Comment by Lissbrict** [comment]
#### The result of Use `AspNet.Security.OAuth.Introspection` lib deserializes the `access_token`

- User.Claims
    - ....
    - "http://schemas.microsoft.com/ws/2008/06/identity/claims/role": "Driver" 

#### The result of Use `AspNet.Security.OAuth.Introspection` lib deserializes the `access_token`

- User.Claims
    - ....
    - `"role": "Driver"` 

### why the role key is  `role`  not  `http://schemas.microsoft.com/ws/2008/06/identity/claims/role`

**Comment by Lissbrict** [comment]
I retrieve the access_token from the Authorization Server, and use this token to access the Resource Server, but when resource server deserialize the access_token, the `User.Claims` property contains the role claim with the key: `role`, and the expected key should be: `http://schemas.microsoft.com/ws/2008/06/identity/claims/role`, what's the problem?

**Comment by PinpointTownes** [comment]
That's because the introspection endpoint automatically converts the `ClaimTypes.Role` claims to `role`, to match the JWT conventions. When the introspection middleware receives a "role" claim, it doesn't map it back to `ClaimTypes.Role` and that's why the types differ between the validation and the introspection middleware.

I'll think a bit more about it to see if I can come up with a better approach.

**Comment by PinpointTownes** [comment]
For the record, the JWT -> WS-Fed claims mapping will be completely removed as part of https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/pull/57, but you'll be able to override the default role claim used by `ClaimsPrincipal.IsInRole` by replacing `OAuthIntrospectionOptions.RoleClaimType` (default value: "role").
