### ISSUE TITLE
There is no sdk version in global.json file

### ISSUE THREAD

**Issue by Jamesxql** [aspnet-contrib/AspNet.Security.OAuth.Extensions#50]
I think you should specify the sdk version in the global.json file, otherwise the visual studio will use the newest sdk version and report an error like this: 

![123](https://cloud.githubusercontent.com/assets/10518551/21159191/32ecae68-c1bb-11e6-9f6b-04c07858af81.png)

**Comment by PinpointTownes** [comment]
Fixed: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/commit/bc84ae875015f68c26e7823fc3616479527a8116.
