### ISSUE TITLE
Add a SaveToken option

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet-contrib/AspNet.Security.OAuth.Extensions#7]
One will likely be added to the JWT bearer middleware: https://github.com/aspnet/Security/issues/639.

**Comment by PinpointTownes** [comment]
This option was added recently in the JWT middleware and is named `SaveToken`. Updating the title to use the same option name.

**Comment by pjirsa** [comment]
when will this be available via Nuget? or if it is already, what version am i looking for?

**Comment by PinpointTownes** [comment]
@pjirsa the SaveToken option is already available in the JWT bearer middleware developed by MSFT. You need to use the latest RC2 nightly builds from the aspnetcidev feed to see it. 

Our validation / introspection middleware don't have this option yet.

**Comment by pjirsa** [comment]
i see. well, that doesn't seem to work for dnxcore50

**Comment by PinpointTownes** [comment]
Which version are you using?

**Comment by pjirsa** [comment]
looks like 1.0.0-rc2-16320

**Comment by PinpointTownes** [comment]
It's way too old (the latest version is `1.0.0-rc2-20410`).

**Comment by pjirsa** [comment]
this is the feed i'm using (https://www.myget.org/F/aspnetcidev/api/v3/index.json) and 16320 was the latest available version

**Comment by PinpointTownes** [comment]
https://github.com/aspnet/Announcements/issues/144

**Comment by pjirsa** [comment]
![Thumbs up](http://i.giphy.com/3o7abB06u9bNzA8lu8.gif)
