### ISSUE TITLE
MissingMethodException when usin introspection with ASP.Net Core 2.0

### ISSUE THREAD

**Issue by wertzui** [aspnet-contrib/AspNet.Security.OAuth.Extensions#76]
I wanted to use OAuth Introspection in my .net core 2.0 project.

I used the following code in my Startup.Configure Method that is working in a .net core 1.1 project.
```
app.UseOAuthIntrospection(options =>
{
    options.Authority = new Uri("myUrl"));
    options.ClientId = "myClient";
    options.ClientSecret = "mySecret";
    options.RequireHttpsMetadata = false;
});
```

However at runtime when sending a request, I get the following exception:

> System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Byte[]> Microsoft.Extensions.Caching.Distributed.IDistributedCache.GetAsync(System.String)'.
>    at AspNet.Security.OAuth.Introspection.OAuthIntrospectionHandler.<RetrieveTicketAsync>d__7.MoveNext()
>    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
>    at AspNet.Security.OAuth.Introspection.OAuthIntrospectionHandler.RetrieveTicketAsync(String token)
>    at AspNet.Security.OAuth.Introspection.OAuthIntrospectionHandler.<HandleAuthenticateAsync>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<InitializeAsync>d__48.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

I tried to Upgrade AspNet.Security.OAuth.Introspection to version 2.0.0-preview1-0283 using the myget feed.
But then my app no longer compiles because of this error:

> Error	CS1061	'IApplicationBuilder' does not contain a definition for 'UseOAuthIntrospection' and no extension method 'UseOAuthIntrospection' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)

What do I have to do to make it work with .net core 2.0?

**Comment by kevinchalet** [comment]
> What do I have to do to make it work with .net core 2.0?

Read https://github.com/aspnet/Announcements/issues/262.

**Comment by wertzui** [comment]
Using the new 

```
services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = "???";
    options.DefaultChallengeScheme = "??";
})
.AddOAuthIntrospection(options =>
{
    options.Authority = new Uri("myUrl"));
    options.ClientId = "myClient";
    options.ClientSecret = "mySecret";
    options.RequireHttpsMetadata = false;
});
```

My app now compiles and runs.
However I will always get a 401 response, as the introspection does not get called when using the `[Authorize]` Attribute on my Controller and therefor the current User is still null.

I'm thinking this comes from wrong Schemes. I tried "Bearer" and "introspection" as schemes, but neither seem to work.

**Comment by wertzui** [comment]
Ok, I found the combination that is working:
In your ConfigureServices Method in the Startup class add the following:
```
services.AddAuthentication().AddOAuthIntrospection(options =>
{
    options.Authority = new Uri("myUrl"));
    options.ClientId = "myClient";
    options.ClientSecret = "mySecret";
    options.RequireHttpsMetadata = false;
});
```

This will by default add OAuth Introspection using the Scheme `"Bearer"`, as defined in `OAuthIntrospectionDefaults.AuthenticationScheme`

Then in your (Base-)Controller add the Authorize Attribute defining the Scheme
```
[Authorize(AuthenticationSchemes = OAuthIntrospectionDefaults.AuthenticationScheme)]
```

It may also be possible giving some defaults to `services.AddAuthentication()` but I was unable to get that working.

**Comment by michaelsogos** [comment]
Dear @wertzui ,

I'm facing same issue, but in my case AddOAuthIntrospection() is not available, vs2017 telling that i'm missing some reference.
Which nuget package version are you using?

![image](https://user-images.githubusercontent.com/971120/29491158-0e213430-8553-11e7-88ee-46cd62d0c3b1.png)

**Comment by michaelsogos** [comment]
Sorry @wertzui i forgot to add the nuget package AspNet.Security.OAuth.Introspection , now it is ok :)

**Comment by michaelsogos** [comment]
Dear @wertzui ,

Here again, i configured everything to issue bearer token with OpenIdDict and until i get the token everything is working properly, but when i call a resource server api passing in the header `Authorization: Bearer [token]` everytime i get this issue:
```
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed for user: (null).
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[3]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
info: Microsoft.AspNetCore.Mvc.ChallengeResult[1]
      Executing ChallengeResult with authentication schemes ().
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[12]
      AuthenticationScheme: Identity.Application was challenged.
```

I tried to implement the AddOAuthIntrospection() but nothing changed, i get the same error.
Can you help me found the reason why [Authorize] fail?
From first error i guess that [Authorize] cannot get user, so maybe it is not able to retrieve the bearer token, but i don't know why.

I'm using DotNet Core 2.0 (latest release), AspNet.Security.OAuth.* 2.0.0-preview1-0283, OpenIddict 2.0.0-preview1-0648.

Thanks for your time :)

**Comment by michaelsogos** [comment]
@wertzui sorry again, in the end i figure out what was the issue, it was about missing audience and Authorize(AuthenticationSchemes = "Bearer") as like you said is mandatory to be specified.

Anyway thanks for your help (i mean the above post) it was very useful 👍
