### ISSUE TITLE
Include HttpHeaders from the request with the Introspection request.

### ISSUE THREAD

**Issue by vyfster** [aspnet-contrib/AspNet.Security.OAuth.Extensions#86]
Would be nice to be able to specify a prefix to match incoming HttpHeaders to, which should be included with the Introspection request.  For example, in my case, I have X-Correlation-Id in my requests to help reference transactions / requests that are related.  

At the moment, the Introspection request does not include this header and so therefore gets lost in all the noise in the logging.

I have a done some work and will create a PR for review.

**Comment by kevinchalet** [comment]
Corresponding PR: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/pull/87.

**Comment by vyfster** [comment]
`OnSendIntrospectionRequest` looks like it'll do the job just fine.
