### ISSUE TITLE
Missing portable pdb's?

### ISSUE THREAD

**Issue by NinoFloris** [aspnet-contrib/AspNet.Security.OAuth.Extensions#90]
Looking at stacktraces gives me no line numbers, do you perhaps release on a windows CI/machine?  

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/blob/dev/build/common.props#L13
Would mean there are only portable pdb's included when published on osx/linux, doesn't look correct right?

**Comment by kevinchalet** [comment]
Done.
