### ISSUE TITLE
Safeguard against access_token authentications on openidconnect server routes 

### ISSUE THREAD

**Issue by NinoFloris** [aspnet-contrib/AspNet.Security.OAuth.Extensions#91]
For one app we currently run an asos oidc server together with the app's api routes, auth server and app in one so to say.

Now in this application we set the default scheme to the OAuthValidation handler.
We sign in users on this oidc server via cookie authentication, which is not the default scheme as our api uses access tokens.
However the really dangerous case comes next, when we require authorization on the `oidc/authorize` endpoint, this should always happen through cookie auth, but of course defaults to token auth. 
When you go through the default scheme you've now made all your access_tokens equivalent to a short lived refresh_token, callable from any backend to keep that token alive until the end of days. 

Could some safeguard be installed in the validation handler for this specific case? 
We currently added this safeguard ourselves like so: 
```cs
options.ForwardDefaultSelector = ctx => if (ctx.GetOpenIdConnectRequest() != null) { throw new InvalidOp("Never ever use access_token auth for oidc endpoints, explicitly pass a scheme instead."); else { return null })
```

Let's say I'm glad I caught this before it went into production ;)

**Comment by kevinchalet** [comment]
> Could some safeguard be installed in the validation handler for this specific case?

I'm tempted to say no, for at least 2 reasons:

  - This library doesn't have any direct dependency on the ASOS primitives. If we wanted to detect the presence of an OIDC request, we'd either have to depend on them or use some reflection, which wouldn't be ideal in both cases.

  - It's not something the JWT bearer handler does so it would be really inconsistent and may be a potential trap: folks would be "protected" when using the aspnet-contrib handler but would no longer be safe when moving to the JWT handler.

Ultimately, I believe it's up to the app developer to correctly set up the authentication schemes.

My recommendation for "hybrid apps" has always been to leave cookies as the default scheme and use `[Authorize(AuthenticationSchemes = "Bearer")]` [or a custom scheme provider](https://stackoverflow.com/questions/46464469/how-to-configureservices-authentication-based-on-routes-in-asp-net-core-2-0/46475072#46475072).

FWIW, I don't like the new "forward schemes" thing introduced by @HaoK in 2.1 at all and I'm 100% convinced it shouldn't have been implemented in each handler options but at a global level. If you need path-based scheme resolution, consider going with the custom scheme provider option.

**Comment by NinoFloris** [comment]
Yes exactly, we currently use an ASOS aware authentication handler which switches on the existence of a value from GetOpenIdConnectRequest. On top of that we use the previous fix so no-one however stupid is able to explicitly authenticate against the token while in a ASOS flow. 

That fix through `ForwardDefaultSelector`  is just so I don't have to inherit the handler or run a forked version, in this case it was actually useful (albeit a misuse). In almost all other cases it's complete madness and policy schemes or custom schemes are a much better option.

I think quite a few projects actually don't want to leave cookies as default if it's just to make it easy for ASOS, which is only a small piece of most apps. Writing Authorize, or doing middleware context calls to ChallengeAsync and friends without a scheme is just much more convenient, so devs do that.

For a solution, doing a one time reflection check for a type isn't the worst downside right?

(pseudo)
```cs
public class AuthHandler 
{

private static Func<HttpContext, bool> GetOIDCFeatureFunc() 
{
    var t = Type.GetType("AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerFeature");
    if (t == null) { return (ctx) => false; }

    return (ctx) => ctx.Features[t] != null;    
}
// Not static to prevent wrong type initialization order from messing with finding feature type 
// Could solve that in a thousand other ways of course
private Func<HttpContext, bool> InASOSFlow { get; } = GetOIDCFeatureFunc();
...


``` 

I just think for something that's frequently used together it might be worth it, with the current aspnet auth stack being application global etc.
