### ISSUE TITLE
Plans for the aspnet-contrib introspection, validation and server middleware for ASP.NET Core 3.0

### ISSUE THREAD

**Issue by kevinchalet** [aspnet-contrib/AspNet.Security.OAuth.Extensions#93]
As part of the incoming work for supporting ASP.NET Core 3.0, I'm seriously consider merging the aspnet-contrib introspection, validation and server middleware into OpenIddict, which would become ASP.NET 4.x/OWIN-compatible and would include a degraded/bare mode offering the same low-level and stateless experience as ASOS and the other aspnet-contrib middleware.

A complete description of my plan can be found here: https://github.com/openiddict/openiddict-core/issues/736.

Got any questions or remarks? Feel free to share them here or on Gitter!

**Comment by danieljee** [comment]
I'm willing to contribute but are [these](https://github.com/openiddict/openiddict-core/labels/help%20wanted) the only things that people can work on?

I'd like to try to add JWT validation in the validation handler just like in OpenIdConnectServerHandler.
